[project]
name = "cookflow"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.0",
    "dotenv>=0.9.9",
    "fastapi>=0.128.0",
    "psycopg2-binary>=2.9.11",
    "uvicorn>=0.40.0",
]
